# Generated by Django 2.1.7 on 2019-04-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190420_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='digest',
            field=models.TextField(default='', verbose_name='摘要'),
        ),
    ]
